# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-30 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.CharField(default=None, max_length=20, unique=True, verbose_name='Uid')),
                ('Name', models.CharField(default=None, max_length=20, verbose_name='Name')),
                ('Cash', models.IntegerField(default=5)),
                ('MAC', models.CharField(default=None, max_length=20, verbose_name='MAC')),
                ('Rate', models.FloatField(default=0.0)),
                ('Coord_x', models.FloatField(default=0.0)),
                ('Coord_y', models.FloatField(default=0.0)),
                ('Password', models.CharField(default=None, max_length=20, verbose_name='Password')),
                ('PhoneNumber', models.CharField(default=None, max_length=20, verbose_name='PhoneNumber')),
                ('Provider', models.CharField(default=None, max_length=20, verbose_name='Provider')),
            ],
        ),
    ]
