# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-31 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_access',
            name='Status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='db_access',
            name='Coord_x',
            field=models.FloatField(default=0.0, max_length=25),
        ),
        migrations.AlterField(
            model_name='db_access',
            name='Coord_y',
            field=models.FloatField(default=0.0, max_length=25),
        ),
    ]
