# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-30 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodent_DB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodent_db',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='prodent_db',
            name='Title',
        ),
        migrations.AddField(
            model_name='prodent_db',
            name='Cash',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='prodent_db',
            name='Coord_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prodent_db',
            name='Coord_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prodent_db',
            name='Mac',
            field=models.CharField(default=None, max_length=20, verbose_name='Mac'),
        ),
        migrations.AddField(
            model_name='prodent_db',
            name='Name',
            field=models.CharField(default=None, max_length=20, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='prodent_db',
            name='Rate',
            field=models.FloatField(default=0.0),
        ),
    ]
