# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-30 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodent_DB', '0002_auto_20180730_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodent_db',
            name='Title',
            field=models.CharField(default=None, max_length=20, verbose_name='TITLE'),
        ),
    ]
