# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-30 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prodent_DB', '0003_prodent_db_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodent_db',
            name='Title',
        ),
    ]
