# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-30 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prodent_DB', '0004_remove_prodent_db_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodent_DB',
            new_name='DB_access',
        ),
    ]
