# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-30 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodent_DB', '0005_auto_20180730_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_access',
            name='Mac',
        ),
        migrations.AddField(
            model_name='db_access',
            name='MAC',
            field=models.CharField(default=None, max_length=20, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='db_access',
            name='Name',
            field=models.CharField(default=None, max_length=20, unique=True, verbose_name='Name'),
        ),
    ]
