# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-30 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodent_DB', '0006_auto_20180730_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_access',
            name='Carrier',
            field=models.CharField(default=None, max_length=20, verbose_name='Carrier'),
        ),
        migrations.AddField(
            model_name='db_access',
            name='Id',
            field=models.CharField(default=None, max_length=20, unique=True, verbose_name='Id'),
        ),
        migrations.AddField(
            model_name='db_access',
            name='Password',
            field=models.CharField(default=None, max_length=20, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='db_access',
            name='PhoneNumber',
            field=models.CharField(default=None, max_length=20, verbose_name='PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='db_access',
            name='Name',
            field=models.CharField(default=None, max_length=20, verbose_name='Name'),
        ),
    ]
