# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-30 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodent_DB', '0007_auto_20180730_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_access',
            name='Id',
            field=models.CharField(default=None, max_length=20, unique=True, verbose_name='Uid'),
        ),
    ]
